--
-- PostgreSQL database dump
--

-- Dumped from database version 16.4
-- Dumped by pg_dump version 16.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: neumonia; Type: TYPE; Schema: public; Owner: postgres
--

CREATE TYPE public.neumonia AS ENUM (
    'N',
    'V',
    'B',
    'M'
);


ALTER TYPE public.neumonia OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Imagen; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Imagen" (
    id_imagen integer NOT NULL,
    nombre_imagen text NOT NULL,
    tipo_imagen text NOT NULL,
    fecha_carga date DEFAULT CURRENT_TIMESTAMP NOT NULL,
    tipo_neumonia public.neumonia NOT NULL,
    probabilidad double precision NOT NULL,
    id_usuario integer NOT NULL
);


ALTER TABLE public."Imagen" OWNER TO postgres;

--
-- Name: Usuario; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Usuario" (
    id_usuario integer NOT NULL,
    nombre text,
    apellido text,
    correo text NOT NULL,
    nombre_usuario text NOT NULL,
    "contraseña" text NOT NULL,
    fecha_creacion date DEFAULT CURRENT_TIMESTAMP NOT NULL,
    estado integer DEFAULT 1 NOT NULL
);


ALTER TABLE public."Usuario" OWNER TO postgres;

--
-- Name: Usuario_id_usuario_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Usuario" ALTER COLUMN id_usuario ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Usuario_id_usuario_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: imagen_id_imagen_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Imagen" ALTER COLUMN id_imagen ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.imagen_id_imagen_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Usuario Usuario_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Usuario"
    ADD CONSTRAINT "Usuario_pkey" PRIMARY KEY (id_usuario);


--
-- Name: Usuario correo_unique; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Usuario"
    ADD CONSTRAINT correo_unique UNIQUE (correo);


--
-- Name: Imagen imagen_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Imagen"
    ADD CONSTRAINT imagen_pkey PRIMARY KEY (id_imagen);


--
-- Name: Usuario nombre_usuario_unique; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Usuario"
    ADD CONSTRAINT nombre_usuario_unique UNIQUE (nombre_usuario);


--
-- Name: Imagen fk_imagen_usuario; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Imagen"
    ADD CONSTRAINT fk_imagen_usuario FOREIGN KEY (id_usuario) REFERENCES public."Usuario"(id_usuario);


--
-- PostgreSQL database dump complete
--

